### ISSUE TITLE
Not working correctly for viewport dimensions

### ISSUE THREAD

**Issue by Mantish** [culshaw/srcset#5]
if I have this:

```
<img src="img.jpg" srcset="img-phone.jpg 400w, img.jpg 800w">
```

It should load img-phone.jpg in a viewport 400px wide and below. Instead it gets load at 799px and below.

**Comment by JayCarney** [comment]
I can confirm this issue, the [W3 draft](http://www.w3.org/html/wg/drafts/srcset/w3c-srcset/) states:

> The attribute essentially takes a comma-separated list of URLs each with one or more descriptors giving the **maximum** viewport dimensions and pixel density allowed to use the image

and then goes to on to clarify:

> where "100w" means "**maximum viewport width** of 100 CSS pixels", "100h" is the same but for height, and "2x" means "**maximum pixel density** of 2 device pixels per CSS pixel"

It appears that the pollyfill is actually working the wrong way around. Personally I think that matching against min is a far better option, and the spec should be changed, but for now the spec does say maximum

**Comment by culshaw** [comment]
Ok will be able to look at this in the next few days, in the meantime, if anyone wants to make a pull request, you are more than welcome :)

**Comment by fschwaiger** [comment]
Absolutely, tried this as well and as soon as i switch less than / greater than symbols it works nicely as intended.
Probably the meaning of "continue" in the source code is ambiguous.

See https://github.com/culshaw/srcset/pull/9

**Comment by culshaw** [comment]
Merging!
